// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onDeviceStatusChange();
void onMotorRunoutChange();
void onMotorSpeedChange();
void onMotorDirectionChange();
void onMotorEnableChange();

String device_status;
float median_Carbon;
float median_Temp;
float motor_runout;
float motor_speed;
bool motor_direction;
bool motor_enable;

void initProperties(){

  ArduinoCloud.addProperty(device_status, READWRITE, ON_CHANGE, onDeviceStatusChange);
  ArduinoCloud.addProperty(median_Carbon, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(median_Temp, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(motor_runout, READWRITE, ON_CHANGE, onMotorRunoutChange);
  ArduinoCloud.addProperty(motor_speed, READWRITE, ON_CHANGE, onMotorSpeedChange);
  ArduinoCloud.addProperty(motor_direction, READWRITE, ON_CHANGE, onMotorDirectionChange);
  ArduinoCloud.addProperty(motor_enable, READWRITE, ON_CHANGE, onMotorEnableChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
