// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)


String macAddress;
float carbon;
float mean_Carbon;
float mean_Temp;
float median_Carbon;
float median_Temp;
CloudIlluminance brightness;
CloudRelativeHumidity humidity;
CloudPressure pressure;
bool carbon_Dir;
bool temp_Dir;
CloudTemperature temperature;

void initProperties(){

  ArduinoCloud.addProperty(macAddress, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(carbon, READ, 15 * SECONDS, NULL);
  ArduinoCloud.addProperty(mean_Carbon, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(mean_Temp, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(median_Carbon, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(median_Temp, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(brightness, READ, 15 * SECONDS, NULL);
  ArduinoCloud.addProperty(humidity, READ, 15 * SECONDS, NULL);
  ArduinoCloud.addProperty(pressure, READ, 15 * SECONDS, NULL);
  ArduinoCloud.addProperty(carbon_Dir, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temp_Dir, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperature, READ, 15 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
